### ISSUE TITLE
Ability to Get a track by ID

### ISSUE THREAD

**Issue by andrewevansumg** [Ringobot/SpotifyApi.NetCore#2]
Hi Daniel. Firstly, thanks for all your work on this, it's saved me loads of time in the last week at work. So thanks :)

Is a ITracksAPI on the way with a track GET function?
 e.g. public async Task<TrackResult> GetTrack(string trackId)
        https://developer.spotify.com/console/get-track/

If not, then I'll look to contribute sometime in the next week or two.

**Comment by DanielLarsenNZ** [comment]
Hey @andrewevansumg ! I'm happy to implement this, won't take me too long. Should have a new version ready by Monday UTC OK?

**Comment by DanielLarsenNZ** [comment]
All set @andrewevansumg . Let me know if any issues.

`Install-Package SpotifyApi.NetCore -Version 2.1.0`

**Comment by andrewevansumg** [comment]
Amazing, you are a legend, thanks.
