### ISSUE TITLE
Implement v1/artists/{id}/albums in ArtistsApi

### ISSUE THREAD

**Issue by brandongregoryscott** [Ringobot/SpotifyApi.NetCore#20]
**Info**
Implement a call for the `v1/artists/{id}/albums` endpoint in the `ArtistsApi` class. I believe this is the last remaining endpoint that needs to be implemented for artists, so that would wrap up coverage there.

Follow existing patterns to have an overload returning `T` to let the consumer handle conversion, and one returning `Album[]`. Add an integration test for each method.

**Reference**
https://developer.spotify.com/documentation/web-api/reference/artists/get-artists-albums/

**Comment by DanielLarsenNZ** [comment]
Hey @brandongregoryscott - I'm happy to do this tonight, or do you have a PR?

**Comment by brandongregoryscott** [comment]
> Hey @brandongregoryscott - I'm happy to do this tonight, or do you have a PR?

I didn't get started on them yet, but I was planning on working on one or both of these in my free time if no one else wanted to take them. Doesn't need to be done ASAP, but I figured I'd open issues to document them

**Comment by DanielLarsenNZ** [comment]
Nice! All yours - and thanks!

**Comment by CamK06** [comment]
Any updates? I'm kinda in need of this for something I'm working on so it would be quite helpful

**Comment by DanielLarsenNZ** [comment]
Hey @Starman0620  - I will have this done by Wednesday.

**Comment by DanielLarsenNZ** [comment]
@Starman0620 there is a preview release for this: https://www.nuget.org/packages/SpotifyApi.NetCore/3.1.0-preview

I just have tests to complete before 3.1.0 release.

**Comment by DanielLarsenNZ** [comment]
Completed in v3.1.0 https://github.com/Ringobot/SpotifyApi.NetCore/releases/tag/3.1.0

**Comment by brandongregoryscott** [comment]
Thanks for taking care of this @DanielLarsenNZ!
