### ISSUE TITLE
Implement v1/browse/new-releases in BrowseApi

### ISSUE THREAD

**Issue by brandongregoryscott** [Ringobot/SpotifyApi.NetCore#21]
**Info**
Implement a call for the `v1/browse/new-releases` endpoint in the `BrowseApi` class. 

Follow existing patterns to have an overload returning `T` to let the consumer handle conversion, and one returning `Album[]`. Add an integration test for each method.

**Reference**
https://developer.spotify.com/documentation/web-api/reference/browse/get-list-new-releases/

**Comment by DanielLarsenNZ** [comment]
Same here @brandongregoryscott - happy to do this tonight, but let me know if you are planning on doing a PR

**Comment by brandongregoryscott** [comment]
> Same here @brandongregoryscott - happy to do this tonight, but let me know if you are planning on doing a PR

Same here - no rush on these, but these are the next two endpoints I'd probably like to integrate with my app. Just documenting them for one of us to tackle when we have time.

**Comment by DanielLarsenNZ** [comment]
Starting this now

**Comment by DanielLarsenNZ** [comment]
Pre-release available now: https://www.nuget.org/packages/SpotifyApi.NetCore/3.1.0-preview

**Comment by DanielLarsenNZ** [comment]
Completed in v3.1.0 https://github.com/Ringobot/SpotifyApi.NetCore/releases/tag/3.1.0
