### ISSUE TITLE
where are SpotifyApi.NetCore.Samples

### ISSUE THREAD

**Issue by badhras** [Ringobot/SpotifyApi.NetCore#24]
The readme mentions sample code in "SpotifyApi.NetCore.Samples" but I'm unsure where to find those samples. Did i miss a samples folder, or is the intent now to learn solely from test case code?

**Comment by DanielLarsenNZ** [comment]
Hi @badhras - Samples have been moved to a separate repo: https://github.com/Ringobot/SpotifyApi.NetCore.Samples

See also #22 which has more info
