### ISSUE TITLE
Enhancement: Add Track Search Functionality

### ISSUE THREAD

**Issue by aevansme** [Ringobot/SpotifyApi.NetCore#4]
Me again! Hi Daniel.

Thanks for your changes, much appreciated :) . I've tried to get this up and running locally so I can submit as a pull request for one small change but I'm not having much luck. Anyway, I feel a GetTrackBySearch method would be helpful if we are trying to query by something other than trackId. Any chance you'd consider adding this in?

https://developer.spotify.com/console/get-search-item/?q=isrc%3AGBAAA1200728&type=track&market=&limit=&offset=

Here are my rough suggested changes (unfortunately I can't build the project to run it).

`       #region GetTracksBySearch

        /// <summary>
        /// Get Spotify catalog information for a single track identified by the query supplied.
        /// </summary>
        /// <param name="query">The Spotify query for the track.</param>
        /// <returns>Task of Track</returns>
        public Task<Track> GetTrackBySearch(string query) => GetTrackBySearch<Track>(query);

        /// <summary>
        /// Get Spotify catalog information for a single track identified by the query supplied.
        /// </summary>
        /// <param name="query">The Spotify query for the track.</param>
        /// <returns>Task of T. The Spotify response is deserialised as T.</returns>
        public async Task<T> GetTrackBySearch<T>(string query)
        {
            string url = $"{BaseUrl}/search?{query}&type=track&limit=1";
            return await GetModel<T>(url);
        }

        #endregion`

`       
        [TestCategory("Integration")]
        [TestMethod]
        public async Task GetTrackBySearch_Isrc_CorrectTrackArtist()
        {
            // arrange
            const string isrc = "5lA3pwMkBdd24StM90QrNR";
            const string query = "q=isrc:" + isrc;

            var http = new HttpClient();
            var accounts = new AccountsService(http, TestsHelper.GetLocalConfig());

            var api = new TracksApi(http, accounts);

            // act
            var response = await api.GetTrackBySearch(query);

            // assert
            Assert.AreEqual("Swedish House Mafia", response.Name);
        }`

**Comment by DanielLarsenNZ** [comment]
Hey Andrew,

This is cool! Go ahead and submit the PR and we can work on it together. The only thing I can see is a missing `await` keyword on the first method? Also, let’s add a limit param- I have a limit offset tuple pattern that I can contribute for this.

So sorry that you can’t get your environment up and running. I blame my lack of documentation! Let me fix this as well and you can test it for me.

🎉🎉🎉

**Comment by DanielLarsenNZ** [comment]
This will be fixed by #5

**Comment by DanielLarsenNZ** [comment]
@aevansme This has been implemented in v2.3.1. 

`dotnet add package SpotifyApi.NetCore --version 2.3.1`

I took the opportunity to refactor the search methods into a new `SearchApi`. I also wrote you an ISRC helper (extension method). So, now you can do this:

```csharp
using SpotifyApi.NetCore;
using SpotifyApi.NetCore.Extensions;
//...
var api = new TracksApi(http, accounts);
var track = await api.GetTrackByIsrcCode("GBBKS1700108");
```

Let me know if any issues! 👍

**Comment by DanielLarsenNZ** [comment]
v2.3.0 has been removed. Use v2.3.1 instead 👍

**Comment by andrewevansumg** [comment]
why are you such an absolute legend? I had every intention of making that change. Thanks a lot!! :)
