### ISSUE TITLE
Image width and height are nullable

### ISSUE THREAD

**Issue by DanielLarsenNZ** [Ringobot/SpotifyApi.NetCore#6]
Image width and height are null if not known:
https://developer.spotify.com/documentation/web-api/reference/object-model/#image-object

These should be represented as nullable int in the Image model :(

This will be a breaking change in vNext

**Comment by brandongregoryscott** [comment]
@DanielLarsenNZ Can this issue be closed out now with the v3.0.1 release?

**Comment by DanielLarsenNZ** [comment]
Yes! Thanks again 👍
